### ISSUE TITLE
I dont know but may be this application is not good :)) Image import from library

### ISSUE THREAD

**Issue by nqmgaming** [IamAbhinavSINGH/DocScanner#4]
![Screenshot_1716914854](https://github.com/IamAbhinavSINGH/DocScanner/assets/94773751/10e5036e-4b91-4ebf-ae18-b508bf89c7ff)

**Comment by nqmgaming** [comment]
I just code an app use GmsDocumentScanner and I have same proplem maybe it auto scan

**Comment by IamAbhinavSINGH** [comment]
@nqmgaming yes, it auto scans from the preview
